"""
Streamlit 표(st.dataframe)에 쓸 표시용 영문 -> 한글 헤더 매핑.

- 네이버 API 동기화, FastAPI `/analytics/*` JSON, DB 컬럼명은 영문 스키마 그대로 유지한다.
- 이 모듈은 `services/data_grid.py` 등 UI 그리드 직전에서만 사용한다.
"""

from __future__ import annotations

COLUMN_MAP: dict[str, str] = {
    "order_id": "상품주문번호",
    "date": "매출 집계일(달력)",
    "date_label": "매출 집계일(달력)",
    "aggregation_window_kst": "매출집계일 안내",
    "payment_date": "결제일시",
    "buyer_name": "구매자명",
    "buyer_id": "구매자ID",
    "receiver_name": "수령인",
    "short_address": "주소",
    "order_count": "주문건수",
    "total_orders": "주문 수",
    "total_sales": "매출",
    "product_name": "상품명",
    "option_name": "옵션상품명",
    "option_product_label": "옵션상품명",
    "order_date": "주문일(달력)",
    "total_amount": "매출",
    "avg_ticket": "평균 객단가",
    "total_quantity": "총 수량",
    "product_group": "상품군",
    "real_quantity": "수량집계",
    "sold_quantity": "판매수량",
    "sales_share_pct": "매출비중(%)",
    "amount_per_order": "주문당 매출",
    "current_revenue": "당일매출",
    "prev_revenue": "전주매출",
    "revenue_diff": "증감매출",
    "revenue_diff_pct": "증감률(%)",
    "today_order_qty": "오늘 주문수량",
    "today_sold_qty": "오늘 판매수량",
    "today_revenue": "오늘 매출",
    "price_diff_pct": "가격변동(%)",
    "nextday_forecast_revenue": "내일예상매출",
    "forecast_short": "단기예측(일평균)",
    "forecast_medium": "중기예측(일평균)",
    "forecast_balanced": "보합예측",
    "forecast_upper": "상한참고",
    "change_reason": "증감 발생 추정 사유",
    "base_day_qty": "기준일 주문수량",
    "order_1_qty": "주문① 수량",
    "order_2_qty": "주문② 수량",
    "order_3_qty": "주문③ 수량",
    "order_4_qty": "주문④ 수량",
    "order_5_qty": "주문⑤ 수량",
    "order_6_qty": "주문⑥ 수량",
    "recent_7d_qty_sum": "최근7일 수량합",
    "prev_7d_qty_sum": "이전7일 수량합",
    "weekly_qty_diff": "주간 증감수량",
    "weekly_qty_diff_pct": "주간 증감률(수량,%)",
    "recent_30d_qty_sum": "최근30일 수량합",
    "prev_30d_qty_sum": "이전30일 수량합",
    "monthly_qty_diff": "월간 증감수량",
    "monthly_qty_diff_pct": "월간 증감률(수량,%)",
    "next_7d_qty_forecast": "다음7일 예상수량",
    "base_day_rev": "기준일 매출",
    "order_1_rev": "매출①",
    "order_2_rev": "매출②",
    "order_3_rev": "매출③",
    "order_4_rev": "매출④",
    "order_5_rev": "매출⑤",
    "order_6_rev": "매출⑥",
    "recent_7d_rev_sum": "최근7일 매출합",
    "prev_7d_rev_sum": "이전7일 매출합",
    "weekly_rev_diff": "주간 증감매출",
    "weekly_rev_diff_pct": "주간 증감률(매출,%)",
    "recent_30d_rev_sum": "최근30일 매출합",
    "prev_30d_rev_sum": "이전30일 매출합",
    "monthly_rev_diff": "월간 증감매출",
    "monthly_rev_diff_pct": "월간 증감률(매출,%)",
    "next_7d_rev_forecast": "다음7일 예상매출",
    "forecast_confidence": "예측 신뢰도",
    "segment": "고객구간",
    "order_count_lifetime": "누적주문일수",
    "revenue_lifetime": "누적순매출",
    "last_order_date": "최근주문일",
    "recent_order_date": "최근주문일",
    "order_1_date": "주문①",
    "order_2_date": "주문②",
    "order_3_date": "주문③",
    "order_4_date": "주문④",
    "order_5_date": "주문⑤",
    "previous_order_date": "이전주문일",
    "reorder_days": "재주문기간(일)",
    "top_option_product": "주요옵션(Top1)",
    "top_option_order_count": "주요옵션 주문횟수",
    "top_option_revenue": "주요옵션 누적순매출",
    "top_option_revenue_share_pct": "주요옵션 매출비중(%)",
    "avg_cycle_days": "평균주기(일)",
    "expected_next_order_date": "예상재주문일",
    "delay_days": "지연일",
    "priority_score": "우선순위점수",
    "recommended_action": "권장 액션",
    "delivery_fee_type": "배송유형",
    "estimated_cost": "추정원가",
    "margin_amount": "마진액",
    "margin_rate_pct": "마진율(%)",
    "customer_paid_shipping": "고객부담배송비",
    "seller_shipping_burden": "판매자배송부담",
    "quantity": "수량",
    "amount": "금액(판매)",
    "net_revenue": "순매출",
    "refund_amount": "환불금액",
    "cancel_amount": "취소금액",
    "revenue_status": "매출상태",
    "revenue_basis": "매출집계기준",
    "order_business_date": "주문 기준 영업일",
    "payment_business_date": "결제 기준 영업일",
    "shipping_business_date": "발송 기준 영업일",
    "revenue": "매출",
    "orders": "주문 수",
    "order_quantity": "주문수량",
    "cancel_count": "취소건수",
    "cancel_rate_pct": "취소율(%)",
    "multiplier": "배수",
    "address": "전체주소",
    "business_date": "매출 집계일",
    "order_calendar_date": "주문일(날짜)",
    "ordered_at": "주문일시",
    "placed_order_at": "발주처리일시",
    "shipped_at": "발송처리일시",
    "order_status": "주문상태",
    "content_order_no": "주문번호",
    "today_revenue": "오늘 매출",
    "total_profit": "총 이익",
    "profit": "이익",
    "hour_of_day": "시간(시)",
    "weekday_num": "요일번호",
    "weekday": "요일",
}

COLUMN_DISPLAY_ORDER: list[str] = [
    "매출 집계일(달력)",
    "매출",
    "매출비중(%)",
    "주문당 매출",
    "평균 객단가",
    "주문건수",
    "판매수량",
    "총 수량",
    "매출집계일 안내",
    "날자",
    "상품주문번호",
    "주문번호",
    "주문일(날짜)",
    "주문일시",
    "발주처리일시",
    "발송처리일시",
    "결제일시",
    "구매자명",
    "구매자ID",
    "수령인",
    "주소",
    "상품명",
    "옵션상품명",
    "수량",
    "수량집계",
    "영업일",
    "주문상태",
]

__all__ = ["COLUMN_MAP", "COLUMN_DISPLAY_ORDER"]
